### ISSUE TITLE
delete backgroud of image

### ISSUE THREAD

**Issue by imvisp** [imvisp/Alien_invasion#1]
delete the background of alien_copy.bmp 
this file is in image folder.
-don't reduce the size of alien.

**Comment by kulendu** [comment]
Hey @imvisp can I work on this issue

**Comment by akhileshthite** [comment]
@imvisp  Hey! I would love to work on this issue. Can you assign me this one?

**Comment by imvisp** [comment]
> @imvisp Hey! I would love to work on this issue. Can you assign me this one?

yes, you can work on it.

**Comment by imvisp** [comment]
> @imvisp Hey! I would love to work on this issue. Can you assign me this one?

hey can you please reopen that PR i just deleted the old one by mistake, sorry :disappointed:

**Comment by akhileshthite** [comment]
> > @imvisp Hey! I would love to work on this issue. Can you assign me this one?
> 
> hey can you please reopen that PR i just deleted the old one by mistake, sorry 😞

Yah! wait.

**Comment by imvisp** [comment]
> @imvisp Hey! I would love to work on this issue. Can you assign me this one?

ok i just reopen that and mearge it once again sorry for everything.

**Comment by akhileshthite** [comment]
> > @imvisp Hey! I would love to work on this issue. Can you assign me this one?
> 
> ok i just reopen that and mearge it once again sorry for everything.

Merged! great :)

**Comment by imvisp** [comment]
th

> > > @imvisp Hey! I would love to work on this issue. Can you assign me this one?
> > 
> > 
> > ok i just reopen that and mearge it once again sorry for everything.
> 
> Merged! great :)

thank you :+1:
